// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttyvacifkgvnwlqjxqil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0eXZhY2lma2d2bndscWp4cWlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MzkzMjgsImV4cCI6MjA2NjAxNTMyOH0.4MgD63QQjUUKN90LoeH5AubzWoiKLNfp00pjEIMk5MQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);